### ISSUE TITLE
npm run dev的时候报错

### ISSUE THREAD

**Issue by developer-liya** [berialjs/berial#23]
micro-front-end/berial/src/index.ts(3,10): semantic error TS2305: Module '"./proxy"' has no exported member 'produce'.

**Comment by yisar** [comment]
现在的 demo 还没更新，今晚回去我会写一个能跑通的 demo，不要着急

**Comment by developer-liya** [comment]
哈哈 ，正好业务需要做下技术调研，加油

**Comment by yisar** [comment]
https://github.com/berialjs/berial/tree/master/example
我写了一个 fre 的 demo，供参考，感谢关注

**Comment by yisar** [comment]
现在有 vue+react+fre 的 demo 啦，俺先关掉，有问题再跟进哈
