### ISSUE TITLE
proxy using with block

### ISSUE THREAD

**Issue by zhang-xiao** [berialjs/berial#41]
https://github.com/berialjs/berial/blob/cd7e742a6048f79e6fd362e7a3fdf83820574c0c/src/html-loader.ts#L116
hi, I wonder if 
`
with(window.IS_BERIAL_SANDBOX) {}
`
should be
`
with(window) {}
`
to proxy window global variables?

**Comment by yisar** [comment]
俺也不太懂这里，改成window就报错

**Comment by yisar** [comment]
我改了，似乎也阔以😭
