### ISSUE TITLE
child app modal style issue

### ISSUE THREAD

**Issue by hansinhu** [berialjs/berial#56]
像模态框组件通常是插入到 body下。
子应用模态框如果插入到parent body下，样式会被shadowDOM隔离

**Comment by yisar** [comment]
可以不加到 body 下，然后直接绝对定位到页面中间

或者如果不得不挂到外面，那样式就只能使用 js 插入到外面了

**Comment by hansinhu** [comment]
> 可以不加到 body 下，然后直接绝对定位到页面中间
> 
> 或者如果不得不挂到外面，那样式就只能使用 js 插入到外面了

是的。
自己写组件还好可以插入到shadowDOM root 。
如果使用了三方组件库，就需要样式插入到外面了。

**Comment by yisar** [comment]
是啊，这个就很惨，沙雕 dom 的样式穿透，是个世纪难题

不使用沙雕的话，他们是咋做的，怎么区分啥时候隔离啥时候不隔离

**Comment by yisar** [comment]
@hansinhu https://github.com/thomaspark/scoper/blob/master/scoper.js 
这里有个兼容性比较好的 runtime 替代方案，类似于 vue style scoped，如果能做成插件就好了

这周我看一下下，似乎可以通过 mixin 的思路搞定
