### ISSUE TITLE
sandbox eval error

### ISSUE THREAD

**Issue by hansinhu** [berialjs/berial#58]
run(code, null) 相当于调用了 null.allowList 而报错

https://github.com/berialjs/berial/blob/1c639d4ef51dc2c14824d752137dea547465c0db/src/sandbox.ts#L1
https://github.com/berialjs/berial/blob/1c639d4ef51dc2c14824d752137dea547465c0db/src/sandbox.ts#L96
https://github.com/berialjs/berial/blob/1c639d4ef51dc2c14824d752137dea547465c0db/src/sandbox.ts#L74

**Comment by yisar** [comment]
这里应该是个对象，哈哈，pr来一个
