### ISSUE TITLE
用await async 代码清晰多了，但是貌似有些问题😊

### ISSUE THREAD

**Issue by j-joker** [berialjs/berial#68]
1.没有等子应用unmonut完就开始mount
2.劫持的子应用路由处理函数没有在应用切换后执行

**Comment by yisar** [comment]
@j-joker 你读的是哪个版本，我最近回滚到旧版本了……之前尝试的版本作废了😭

**Comment by j-joker** [comment]
> @j-joker 你读的是哪个版本，我最近回滚到旧版本了……之前尝试的版本作废了😭

soga
