### ISSUE TITLE
Dome 跑不通，能不能使用安装方式跑一遍 demo. 再基于不同框架试一下（vue、react, angular）

### ISSUE THREAD

**Issue by toweave** [berialjs/berial#70]
![image](https://user-images.githubusercontent.com/12064408/105324731-c0d9f200-5c06-11eb-819f-1c822c37746d.png)

**Comment by yisar** [comment]
我好久没搞了，最近比较忙，就……你可以自己用 umd 的文件一边调试一边跑

**Comment by yisar** [comment]
我现在可以跑通了

**Comment by toweave** [comment]
后面试一下

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年3月25日 13:45
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [berialjs/berial] Dome 跑不通，能不能使用安装方式跑一遍 demo. 再基于不同框架试一下（vue、react, angular） (#70)


我现在可以跑通了

―
